routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/','HomeControllerr@index')->name("home");
Route::get('/single-view/{slug}','HomeControllerr@singlePost')->name("post.single");
Route::get('/all-post','HomeControllerr@allPost')->name("post.all");

Route::get('/catrgory/{slug}','HomeControllerr@categoryPost')->name("category.post");

Route::get('/tag/{slug}','HomeControllerr@tagPost')->name("tag.post");

route::post('subcriber','SubscriberController@store')->name('subscriber.store');

route::get('search','SearchController@search')->name('search');
Auth::routes();

Route::group(['middleware'=>['auth']],function()
{
   route::post('favorite/{id}/add','FavoriteController@add')->name('post.favorite');
   route::post('comment/{id}','CommerntController@store')->name('post.comment');

});
route::get('/comment','CommerntController@view')->name('view.comment');
Route::group(['as'=>'admin.','prefix'=>'admin','namespace'=>'Admin','middleware'=>['auth','admin']],function(){

     route::get("/dashboard","DashboardController@index")->name("dashboard");

     route::get('settings','SettingsController@index')->name('settings');
     route::put('profile-update','SettingsController@profileUpdate')->name('profile.update');
     route::put('password-update','SettingsController@passwordUpdate')->name('password.update');

     route::resource('tag','TagController');

     route::resource('category','CategoryController');

     route::get('favorite','FavoriteController@show')->name('favorite.show');
     
     route::get('post/pending','PostController@pending')->name('post.pending');
     route::put('post/{id}/approved','PostController@approval')->name('post.approved');
     route::resource('post','PostController');
     
     route::get('subscriber','SubscriberController@index')->name('subscriber.index');
     route::delete('subscriber/{id}','SubscriberController@destroy')->name('subscriber.destroy');

     route::get('comments','CommentController@index')->name('comment.index');
     route::delete('comments/{id}','CommentController@destroy')->name('comment.destroy');
     
    

    
});
Route::group(['as'=>'author.','prefix'=>'author','namespace'=>'Author','middleware'=>['auth','author']], function(){

    route::get("/dashboard","DashboardController@index")->name("dashboard");
    route::resource('post','PostController');

    route::get('favorite','FavoriteController@show')->name('favorite.show');

    route::get('settings','SettingsController@index')->name('settings');
    route::put('profile-update','SettingsController@profileUpdate')->name('profile.update');
    route::put('password-update','SettingsController@passwordUpdate')->name('password.update');

    route::get('comments','CommentController@index')->name('comment.index');
     route::delete('comments/{id}','CommentController@destroy')->name('comment.destroy');

});

resources/views/layouts/frontend/inc/footer.blade.php
<footer>

    <div class="container">
        <div class="row">

            <div class="col-lg-4 col-md-6">
                <div class="footer-section">

                    <a class="logo" href="#"><img src="images/logo.png" alt="Logo Image"></a>
                    <p class="copyright">{{ config('app.name') }}</p>
                    <p class="copyright">Developed <a href="https://dcodea.com" target="_blank">Forkan Alam</a></p>
                    <ul class="icons">
                        <li><a href="#"><i class="ion-social-facebook-outline"></i></a></li>
                        <li><a href="#"><i class="ion-social-twitter-outline"></i></a></li>
                        <li><a href="#"><i class="ion-social-instagram-outline"></i></a></li>
                        <li><a href="#"><i class="ion-social-vimeo-outline"></i></a></li>
                        <li><a href="#"><i class="ion-social-pinterest-outline"></i></a></li>
                    </ul>

                </div><!-- footer-section -->
            </div><!-- col-lg-4 col-md-6 -->

            <div class="col-lg-4 col-md-6">
                    <div class="footer-section">
                    <h4 class="title"><b>CATAGORIES</b></h4>
                  @foreach ($cats as $item)
                  <ul>
                    <li><a href="#">{{ $item->name }}</a></li>    
                </ul>
                  @endforeach
                </div><!-- footer-section -->
            </div><!-- col-lg-4 col-md-6 -->

            <div class="col-lg-4 col-md-6">
                <div class="footer-section">

                    <h4 class="title"><b>SUBSCRIBE</b></h4>
                    <div class="input-area">
                        <form action="{{ route('subscriber.store') }}" method="post">
                            @csrf
                            <input class="email-input" type="text" placeholder="Enter your email" name="email">
                            <button class="submit-btn" type="submit"><i class="icon ion-ios-email-outline"></i></button> 
                        </form>
                    </div>
                    <div class="text-danger"> {{ $errors->first('email') }}</div>

                </div><!-- footer-section -->
            </div><!-- col-lg-4 col-md-6 -->

        </div><!-- row -->
    </div><!-- container -->
</footer>

resources/views/layouts/frontend/inc/header.blade.php
 <header>
    <div class="container-fluid position-relative no-side-padding">

        <a href="#" class="logo">{{ config('app.name') }}</a>

        <div class="menu-nav-icon" data-nav-menu="#main-menu"><i class="ion-navicon"></i></div>

        <ul class="main-menu visible-on-click" id="main-menu">
            <li><a href="{{ route('home') }}">Home</a></li>
            <li><a href="#">Categories</a></li>
            <li><a href="{{ route('post.all') }}">Posts</a></li>
            @guest
            <li><a href="{{ route('login') }}">Log In</a></li>
            @else
            @if (Auth::user()->role_id == 1)

            <li><a href="{{ route('admin.dashboard') }}">Dashboard</a></li>
            @else
                <li><a href="{{ route('author.dashboard') }}">Dashboard</a></li>
            @endif
            @endguest
           
        </ul><!-- main-menu -->

        <div class="src-area">
            <form method="GET" action="{{ route('search') }}">
                <button class="src-btn" type="submit"><i class="ion-ios-search-strong"></i></button>
                <input name="query" class="src-input" type="text" placeholder="Type of search">
            </form>
        </div>

    </div><!-- conatiner -->
</header>