routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/','HomeControllerr@index')->name("home");
Route::get('/single-view/{slug}','HomeControllerr@singlePost')->name("post.single");
Route::get('/all-post','HomeControllerr@allPost')->name("post.all");

Route::get('/catrgory/{slug}','HomeControllerr@categoryPost')->name("category.post");

Route::get('/tag/{slug}','HomeControllerr@tagPost')->name("tag.post");

route::post('subcriber','SubscriberController@store')->name('subscriber.store');

route::get('search','SearchController@search')->name('search');
Auth::routes();

Route::group(['middleware'=>['auth']],function()
{
   route::post('favorite/{id}/add','FavoriteController@add')->name('post.favorite');
   route::post('comment/{id}','CommerntController@store')->name('post.comment');

});
route::get('/comment','CommerntController@view')->name('view.comment');
Route::group(['as'=>'admin.','prefix'=>'admin','namespace'=>'Admin','middleware'=>['auth','admin']],function(){

     route::get("/dashboard","DashboardController@index")->name("dashboard");

     route::get('settings','SettingsController@index')->name('settings');
     route::put('profile-update','SettingsController@profileUpdate')->name('profile.update');
     route::put('password-update','SettingsController@passwordUpdate')->name('password.update');

     route::resource('tag','TagController');

     route::resource('category','CategoryController');

     route::get('favorite','FavoriteController@show')->name('favorite.show');
     
     route::get('post/pending','PostController@pending')->name('post.pending');
     route::put('post/{id}/approved','PostController@approval')->name('post.approved');
     route::resource('post','PostController');
     
     route::get('subscriber','SubscriberController@index')->name('subscriber.index');
     route::delete('subscriber/{id}','SubscriberController@destroy')->name('subscriber.destroy');

     route::get('comments','CommentController@index')->name('comment.index');
     route::delete('comments/{id}','CommentController@destroy')->name('comment.destroy');
     
    

    
});
Route::group(['as'=>'author.','prefix'=>'author','namespace'=>'Author','middleware'=>['auth','author']], function(){

    route::get("/dashboard","DashboardController@index")->name("dashboard");
    route::resource('post','PostController');

    route::get('favorite','FavoriteController@show')->name('favorite.show');

    route::get('settings','SettingsController@index')->name('settings');
    route::put('profile-update','SettingsController@profileUpdate')->name('profile.update');
    route::put('password-update','SettingsController@passwordUpdate')->name('password.update');

    route::get('comments','CommentController@index')->name('comment.index');
     route::delete('comments/{id}','CommentController@destroy')->name('comment.destroy');

});

app/Comment.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Comment extends Model
{
    public function post()
    {
        return $this->belongsTo('App\Post');
    }
    public function user()
    {
        return $this->belongsTo('App\User');
    }
}

app/Http/Controllers/Admin/CommentController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Comment;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Brian2694\Toastr\Facades\Toastr;


class CommentController extends Controller
{
   public function index()
   {

       $data['comments'] = Comment::all();
       return view('admin.comment.index',$data);
       
   }
   public function destroy($id)
   {

       $comment = Comment::find($id);
      $comment->delete();
      Toastr::error('comment successfully deleted','Delete');
      return redirect()->back();
       
   }
}

app/Http/Controllers/Author/CommentController.php
<?php

namespace App\Http\Controllers\Author;

use App\Comment;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Brian2694\Toastr\Facades\Toastr;
use Illuminate\Support\Facades\Auth;

class CommentController extends Controller
{
    public function index()
    {
 
        $data['comments'] = Auth::user()->comments;
        
        return view('author.comment.index',$data);
        
    }
    public function destroy($id)
    {
 
        $comment = Comment::find($id);
       $comment->delete();
       Toastr::error('comment successfully deleted','Delete');
       return redirect()->back();
        
    }
}

resources/views/admin/comment/index.blade.php
@extends('layouts.backend.app')

@section('tittle','Post')

@push('css')
<link href="{{ asset('assets/backend/plugins/jquery-datatable/skin/bootstrap/css/dataTables.bootstrap.css"') }}" rel="stylesheet">
@endpush
@section('contant')
<section class="content">
    <div class="container-fluid">
        
       
        <!-- Exportable Table -->
        <div class="row clearfix">
            <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                <div class="card">
                    <div class="header">
                        <h2>
                           Subscribers
                           <span><small>{{ $comments->count() }}</small></span>
                        </h2>
                       
                    </div>
                    <div class="body">
                        <div class="table-responsive">
                            <table class="table table-bordered table-striped table-hover dataTable js-exportable">
                                <thead>

                                  
                                       
                                       <tr>
                                            <th>ID</th>
                                            <th>Commented Post</th>
                                            <th>Commenter</th>
                                            <th>Comment</th>
                                            <th>Created at</th>
                                            <th>Action</th>
                                           
                                        </tr>
                                       
                                

                                </thead>
                                <tfoot>

                                    <tr>
                                        <th>ID</th>
                                        <th>Commented Post</th>
                                        <th>Commenter</th>
                                        <th>Comment</th>
                                        <th>Created at</th>
                                        <th>Action</th>
                                    
                                    </tr>

                                </tfoot>
                                <tbody>
                                       
                                   @foreach ($comments as $key => $item)
                                    <tr>
                                       
                                        <td>{{ $key + 1 }}</td>
                                      
                                        <td>{{ $item->post->title }}</td>
                                        <td>{{ $item->user->name }}</td>
                                        <td>{{ $item->comment }}</td>
                                        <td>{{ $item->created_at->diffForHumans()}}</td>
                                     
                                        <td>
                                            <button type="button"  class="btn btn-danger" onclick="deletePost({{ $item->id }})">Delete</button>
                                            <form id="delete-form-{{ $item->id }}" action="{{ route('admin.comment.destroy',$item->id) }}" method="POST" style="display:none">
                                            @csrf
                                            @method('DELETE')
                                            </form>
                                        </td>
                                    </tr>
                                   @endforeach
                                    
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- #END# Exportable Table -->
    </div>
</section>
@endsection

@push('js')
<script src="{{ asset('assets/backend/plugins/jquery-datatable/jquery.dataTables.js') }}"></script>
<script src="{{ asset('assets/backend/plugins/jquery-datatable/skin/bootstrap/js/dataTables.bootstrap.js') }}"></script>
<script src="{{ asset('assets/backend/plugins/jquery-datatable/extensions/export/dataTables.buttons.min.js') }}"></script>
<script src="{{ asset('assets/backend/plugins/jquery-datatable/extensions/export/buttons.flash.min.js') }}"></script>
<script src="{{ asset('assets/backend/plugins/jquery-datatable/extensions/export/jszip.min.js') }}"></script>
<script src="{{ asset('assets/backend/plugins/jquery-datatable/extensions/export/pdfmake.min.js') }}"></script>
<script src="{{ asset('assets/backend/plugins/jquery-datatable/extensions/export/vfs_fonts.js') }}"></script>
<script src="{{ asset('assets/backend/plugins/jquery-datatable/extensions/export/buttons.html5.min.js') }}"></script>
<script src="{{ asset('assets/backend/plugins/jquery-datatable/extensions/export/buttons.print.min.js') }}"></script>

<script src="{{ asset('assets/backend/js/pages/tables/jquery-datatable.js') }}"></script>
<script src="https://cdn.jsdelivr.net/npm/sweetalert2@8"></script>

<script type="text/javascript">
function deletePost(id)
{
    Swal.fire({
  title: 'Are you sure?',
  text: "You won't be able to revert this!",
  type: 'warning',
  showCancelButton: true,
  confirmButtonColor: '#3085d6',
  cancelButtonColor: '#d33',
  confirmButtonText: 'Yes, delete it!'
}).then((result) => {
  if (result.value) {
    event.preventDefault();
    document.getElementById('delete-form-'+ id).submit();
  }
})

}

</script>
@endpush