routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/','HomeControllerr@index')->name("home");
Route::get('/single-view/{slug}','HomeControllerr@singlePost')->name("post.single");
Route::get('/all-post','HomeControllerr@allPost')->name("post.all");

Route::get('/catrgory/{slug}','HomeControllerr@categoryPost')->name("category.post");

Route::get('/tag/{slug}','HomeControllerr@tagPost')->name("tag.post");

route::post('subcriber','SubscriberController@store')->name('subscriber.store');

route::get('search','SearchController@search')->name('search');
Auth::routes();

Route::group(['middleware'=>['auth']],function()
{
   route::post('favorite/{id}/add','FavoriteController@add')->name('post.favorite');
   route::post('comment/{id}','CommerntController@store')->name('post.comment');

});
route::get('/comment','CommerntController@view')->name('view.comment');
Route::group(['as'=>'admin.','prefix'=>'admin','namespace'=>'Admin','middleware'=>['auth','admin']],function(){

     route::get("/dashboard","DashboardController@index")->name("dashboard");

     route::get('settings','SettingsController@index')->name('settings');
     route::put('profile-update','SettingsController@profileUpdate')->name('profile.update');
     route::put('password-update','SettingsController@passwordUpdate')->name('password.update');

     route::resource('tag','TagController');

     route::resource('category','CategoryController');

     route::get('favorite','FavoriteController@show')->name('favorite.show');
     
     route::get('post/pending','PostController@pending')->name('post.pending');
     route::put('post/{id}/approved','PostController@approval')->name('post.approved');
     route::resource('post','PostController');
     
     route::get('subscriber','SubscriberController@index')->name('subscriber.index');
     route::delete('subscriber/{id}','SubscriberController@destroy')->name('subscriber.destroy');

     route::get('comments','CommentController@index')->name('comment.index');
     route::delete('comments/{id}','CommentController@destroy')->name('comment.destroy');
     
    

    
});
Route::group(['as'=>'author.','prefix'=>'author','namespace'=>'Author','middleware'=>['auth','author']], function(){

    route::get("/dashboard","DashboardController@index")->name("dashboard");
    route::resource('post','PostController');

    route::get('favorite','FavoriteController@show')->name('favorite.show');

    route::get('settings','SettingsController@index')->name('settings');
    route::put('profile-update','SettingsController@profileUpdate')->name('profile.update');
    route::put('password-update','SettingsController@passwordUpdate')->name('password.update');

    route::get('comments','CommentController@index')->name('comment.index');
     route::delete('comments/{id}','CommentController@destroy')->name('comment.destroy');

});

app/Http/Controllers/Author/CommentController.php
<?php

namespace App\Http\Controllers\Author;

use App\Comment;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Brian2694\Toastr\Facades\Toastr;
use Illuminate\Support\Facades\Auth;

class CommentController extends Controller
{
    public function index()
    {
 
        $data['comments'] = Auth::user()->comments;
        
        return view('author.comment.index',$data);
        
    }
    public function destroy($id)
    {
 
        $comment = Comment::find($id);
       $comment->delete();
       Toastr::error('comment successfully deleted','Delete');
       return redirect()->back();
        
    }
}

app/Http/Controllers/Author/DashboardController.php
<?php

namespace App\Http\Controllers\Author;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class DashboardController extends Controller
{
    public function index(){
        return view("author.dashboard");
    }
}

app/Http/Controllers/Author/FavoriteController.php
<?php

namespace App\Http\Controllers\Author;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Auth;

class FavoriteController extends Controller
{
    public function show()
   {
      
    $data['favoritePost'] = Auth::user()->favorite_posts;
    
    return view('author.favorite.index',$data);
    

//    for($i = 0; $i < count($favoritePost); $i++)
//    {
//     foreach ($favoritePost as $key => $value) {
        
//      }
//    }
     
   }
}

app/Http/Controllers/Author/PostController.php
<?php

namespace App\Http\Controllers\Author;

use App\Tag;
use App\Post;
use App\User;
use App\Category;
use Carbon\Carbon;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Brian2694\Toastr\Facades\Toastr;
use Illuminate\Support\Facades\Auth;
use Intervention\Image\Facades\Image;
use Illuminate\Support\Facades\Storage;
use Illuminate\Support\Facades\Notification;
use App\Notifications\NewAuthor;

class PostController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $posts["data"] = Auth::User()->posts()->latest()->get();
        return view('author.post.index',$posts);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $categories['catData'] = Category::all();
        $tags['tagData'] = Tag::all();
        return view('author.post.create',$categories,$tags);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {

        // dd(Auth::User()->name);
        $request->validate([
            'title'=>'required',
            'image'=>'required|image|max:2048',
            'categories'=>'required',
            'tags'=>'required',
            'body'=>'required',
           ]);
    
           
    
        //    dd($image);
           $slug = str_slug($request->title).'-'.uniqid();
           $slugs = str_slug($request->title);
    
          if($request->hasFile('image')){
    
              $image = $request->file('image');
              $currentDate = Carbon::now()->toDateString();
              $imageName = $slugs."-".$currentDate."-".uniqid().Auth::User()->name.".".$image->getClientOriginalExtension(); 
    
              $path = "storage/post/".$imageName;
    
              if(!Storage::disk('public')->exists('post'))
              {
                     Storage::disk('public')->makeDirectory('post');
              }
              $newImage = Image::make($image)->resize(1600,1055)->save($path);
    
            //   Storage::disk('public')->put('post/'.$imageName , $newImage );
    
         }
         else
         {
              $imageName = "default.png";
          }
    
          $post = new Post();
          $post->user_id = Auth::id();
          $post->title = $request->title;
          $post->image = $imageName;
          $post->slug = $slug;
    
          if(isset($request->status))
          {
            $post->status = true;
          }else{
    
            $post->status = false;
          }
          $post->body = $request->body;
          $post->is_approved = false;
    
          $post->save();
    
          $post->categories()->attach($request->categories);
          $post->tags()->attach($request->tags);
    
           $user = User::where('role_id','1')->get();
           Notification::send($user,new NewAuthor($post));

          Toastr::success("success fully added posts","success");
          return redirect()->route("author.post.index");
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Post  $post
     * @return \Illuminate\Http\Response
     */
    public function show(Post $post)
    {

      if($post->user_id != Auth::id())
       {
         Toastr::error('You are no authorized to access this post','error');
         return redirect()->back();
       }
      $categories = Category::all();
      $tags = Tag::all();
      return view('author.post.show',compact('post','categories','tags'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Post  $post
     * @return \Illuminate\Http\Response
     */
    public function edit(Post $post)
    {

       if($post->user_id != Auth::id())
       {
         Toastr::error('You are no authorized to access this post','error');
         return redirect()->back();
       }
        $categories = Category::all();
        $tags = Tag::all();
        return view('author.post.edit',compact('post','categories','tags'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Post  $post
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Post $post)
    {

      if($post->user_id != Auth::id())
       {
         Toastr::error('You are no authorized to access this post','error');
         return redirect()->back();
       }
        $request->validate([
            'title'=>'required',
            'image'=>'image|max:2048',
            'categories'=>'required',
            'tags'=>'required',
            'body'=>'required',
           ]);
    
           
    
        //    dd($image);
           $slug = str_slug($request->title).'-'.uniqid();
           $slugs = str_slug($request->title);
    
          if($request->hasFile('image')){
    
              $image = $request->file('image');
              $currentDate = Carbon::now()->toDateString();
              $imageName = $slugs."-".$currentDate."-".uniqid().".".$image->getClientOriginalExtension(); 
    
              $path = "storage/post/".$imageName;
    
              if(!Storage::disk('public')->exists('post'))
              {
                     Storage::disk('public')->makeDirectory('post');
              }

              if(Storage::disk('public')->exists('post/'.$post->image))
              {
                Storage::disk('public')->delete('post/'.$post->image);
              }
              $newImage = Image::make($image)->resize(1600,1055)->save($path);
    
            //   Storage::disk('public')->put('post/'.$imageName , $newImage );
    
         }
        else
         {
            $imageName = $post->image;
         }
    
          
          $post->user_id = Auth::id();
          $post->title = $request->title;
          $post->image = $imageName;
          $post->slug = $slug;
    
          if(isset($request->status))
          {
            $post->status = true;
          }else{
    
            $post->status = false;
          }
          $post->body = $request->body;
          $post->is_approved = false;
    
          $post->save();
    
          $post->categories()->sync($request->categories);
          $post->tags()->sync($request->tags);
    
          Toastr::success("success fully Updated posts","success");
          return redirect()->route("author.post.index");
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Post  $post
     * @return \Illuminate\Http\Response
     */
    public function destroy(Post $post)
    {
      if($post->user_id != Auth::id())
       {
         Toastr::error('You are no authorized to access this post','error');
         return redirect()->back();
       }
       
      if(Storage::disk('public')->exists("post/".$post->image))
      {
        Storage::disk('public')->delete('post/'.$post->image);
      }


      $post->delete();
      $post->categories()->detach();
      $post->tags()->detach();
      Toastr::success("Post successfully deleted","success");
      return redirect()->back();
    }
}

app/Http/Controllers/Author/SettingsController.php
<?php

namespace App\Http\Controllers\Author;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\User;

use Illuminate\Support\Carbon;

use Illuminate\Support\Facades\Auth;
use Intervention\Image\Facades\Image;
use Illuminate\Support\Facades\Storage;
use Brian2694\Toastr\Facades\Toastr;
use Illuminate\Support\Facades\Hash;

class SettingsController extends Controller
{
  public function index()
  {
      return view('author.settings');
  }

  public function profileUpdate(Request $request)
  {
     $request->validate([
       'name'=>'required',
       'email'=>'required|email',
       'image'=>'required|image',

     ]);


     $image = $request->file('image');
     $slug = str_slug($request->name);
     $user = User::findOrFail(Auth::id());
    
     if(isset($image))
     {
       $currentDate = Carbon::now()->toDateString();
       $imageName = $slug.'-'.$currentDate.'-'.uniqid().'.'.$image->getClientOriginalExtension();

       $path = "storage/profile/".$imageName;
      
       if(!Storage::disk('public')->exists('profile'))
       {
         Storage::disk('public')->makeDirectory('profile');

       }

       if(Storage::disk('public')->exists('profile/'.$user->image))
        {
          Storage::disk('public')->delete('profile/'.$user->image);
        }

       $profile = Image::make($image)->resize(500,500)->save($path);

      //  Storage::disk('public')->put('profile/'.$imageName,$profile);


     }else{
       $imageName = $user->image;
     }
     $user->name = $request->name;
     $user->email = $request->email;
     $user->image = $imageName;
     $user->about = $request->about;
     $user->save();
     Toastr::success('your profile has been updated successfully','success');
     return redirect()->back();
  }

  public function passwordUpdate(Request $request)
    {
      $request->validate([
           'old_password' => 'required',
           'password' => 'required|confirmed',

      ]);
     
      $currentPass = Auth::user()->password;
      if(Hash::check($request->old_password,$currentPass))
      {
        if(!Hash::check($request->password,$currentPass))  
        {
          
          $user = User::find(Auth::id());
          
          $user->password = Hash::make($request->password);
          $user->save();
          Toastr::success('password has been changed successfully','success');
          Auth::logout();
          return redirect()->back();
        } else {
          {
            Toastr::error('Your old password should not match with new password','error');
            return redirect()->back();
          }
        }

      }else{
        Toastr::error('current password does not match with old password','error');
        return redirect()->back();
      }
    }
}

resources/views/author/settings.blade.php
@extends('layouts.backend.app')
@section('title','settings')

@push('css')
    
@endpush


@section('contant')
    
<section class="content">
    <div class="container-fluid">

        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
            <div class="card">
                <div class="header">
                    <h2>
                        TABS WITH ICON TITLE
                    </h2>
                    <ul class="header-dropdown m-r--5">
                        <li class="dropdown">
                            <a href="javascript:void(0);" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
                                <i class="material-icons">more_vert</i>
                            </a>
                            <ul class="dropdown-menu pull-right">
                                <li><a href="javascript:void(0);" class=" waves-effect waves-block">Action</a></li>
                                <li><a href="javascript:void(0);" class=" waves-effect waves-block">Another action</a></li>
                                <li><a href="javascript:void(0);" class=" waves-effect waves-block">Something else here</a></li>
                            </ul>
                        </li>
                    </ul>
                </div>
                <div class="body">
                    <!-- Nav tabs -->
                    <ul class="nav nav-tabs" role="tablist">
                        <li role="presentation" class="active">
                            <a href="#profile_with_icon_title" data-toggle="tab">
                                <i class="material-icons">face</i> Update Profile
                            </a>
                        </li>
                        <li role="presentation">
                            <a href="#password_with_icon_title" data-toggle="tab">
                                <i class="material-icons">fingerprint</i> Password
                            </a>
                        </li>
                        
                    </ul>

                    <!-- Tab panes -->
                    <div class="tab-content">
                        <div role="tabpanel" class="tab-pane fade in active" id="profile_with_icon_title">
                            <b>Home Content</b>
                            <form class="form-horizontal" action="{{ route('author.profile.update') }}" method="POST" enctype="multipart/form-data">
                                @csrf
                                @method('PUT')
                                <div class="row clearfix">
                                    <div class="col-lg-2 col-md-2 col-sm-4 col-xs-5 form-control-label">
                                        <label for="email_address_2">Name</label>
                                    </div>
                                    <div class="col-lg-10 col-md-10 col-sm-8 col-xs-7">
                                        <div class="form-group">
                                            <div class="form-line"> 
                                                <input type="text" id="email_address_2" class="form-control" placeholder="Enter your email address" name="name" value="{{ Auth::user()->name }}">
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <div class="row clearfix">
                                    <div class="col-lg-2 col-md-2 col-sm-4 col-xs-5 form-control-label">
                                        <label for="email_address_2">Email Address</label>
                                    </div>
                                    <div class="col-lg-10 col-md-10 col-sm-8 col-xs-7">
                                        <div class="form-group">
                                            <div class="form-line">
                                                <input type="text" id="email_address_2" class="form-control" placeholder="Enter your email address" name="email" value="{{ Auth::user()->email }}">
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <div class="row clearfix">
                                    <div class="col-lg-2 col-md-2 col-sm-4 col-xs-5 form-control-label">
                                        <label for="email_address_2">Profile Image</label>
                                    </div>
                                    <div class="col-lg-10 col-md-10 col-sm-8 col-xs-7">
                                        <div class="form-group">
                                            <div class="form-line">
                                               <input type="file" name="image">
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <div class="row clearfix">
                                    <div class="col-lg-2 col-md-2 col-sm-4 col-xs-5 form-control-label">
                                        <label for="password_2">About</label>
                                    </div>
                                    <div class="col-lg-10 col-md-10 col-sm-8 col-xs-7">
                                        <div class="form-group">
                                            <div class="form-line">
                                                <textarea class="form-control" name="about" id="" cols="30" rows="10">{{ Auth::user()->about }}</textarea>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                
                             
                                <div class="row clearfix">
                                    <div class="col-lg-offset-2 col-md-offset-2 col-sm-offset-4 col-xs-offset-5">
                                        <button type="submit" class="btn btn-primary m-t-15 waves-effect">Update</button>
                                    </div>
                                </div>
                            </form>
                        </div>
                        <div role="tabpanel" class="tab-pane fade" id="password_with_icon_title">
                            <form class="form-horizontal" action="{{ route('author.password.update') }}" method="POST">
                                @csrf
                                @method('PUT')
                                <div class="row clearfix">
                                    <div class="col-lg-2 col-md-2 col-sm-4 col-xs-5 form-control-label">
                                        <label for="old">Old Password</label>
                                    </div>
                                    <div class="col-lg-10 col-md-10 col-sm-8 col-xs-7">
                                        <div class="form-group">
                                            <div class="form-line"> 
                                                <input type="password" id="old" class="form-control" placeholder="Enter your Old pass" name="old_password" >
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <div class="row clearfix">
                                    <div class="col-lg-2 col-md-2 col-sm-4 col-xs-5 form-control-label">
                                        <label for="new">New Password</label>
                                    </div>
                                    <div class="col-lg-10 col-md-10 col-sm-8 col-xs-7">
                                        <div class="form-group">
                                            <div class="form-line">
                                                <input type="password" id="new" class="form-control" placeholder="Enter your New pass" name="password" >
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <div class="row clearfix">
                                    <div class="col-lg-2 col-md-2 col-sm-4 col-xs-5 form-control-label">
                                        <label for="confirm">Confirm Password</label>
                                    </div>
                                    <div class="col-lg-10 col-md-10 col-sm-8 col-xs-7">
                                        <div class="form-group">
                                            <div class="form-line">
                                                <input type="password" id="confirm" class="form-control" placeholder="Confirm pass" name="password_confirmation">
                                            </div>
                                        </div>
                                    </div>
                                </div>
                             
                               
                                
                             
                                <div class="row clearfix">
                                    <div class="col-lg-offset-2 col-md-offset-2 col-sm-offset-4 col-xs-offset-5">
                                        <button type="submit" class="btn btn-primary m-t-15 waves-effect">Update</button>
                                    </div>
                                </div>
                            </form>
                        </div>
                        
                      
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>


@endsection

@push('js')
    
@endpush